version: '3'
services:
  flask_app:
    build: .
    ports:
      - "0.0.0.0:5000:5000"  # Expose Flask app to outer environment
    depends_on:
      - splash

  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"  # Expose Splash to other containers