name: deploy-to-ecs

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAXYKJQPHGOWU3EE6S"
          aws-secret-access-key: "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"
          aws-region: "us-east-1"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533266987468.dkr.ecr.us-east-1.amazonaws.com/amazon-insights

      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3-dev
        
      - name: Set up QEMU for arm64
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: runner.os == 'Linux'

      - name: Set up Docker for arm64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker build --platform linux/arm64 -t amazon-review-insights .
          docker tag amazon-review-insights:latest 533266987468.dkr.ecr.us-east-1.amazonaws.com/amazon-insights/amazon-review-insights:latest
          docker push 533266987468.dkr.ecr.us-east-1.amazonaws.com/amazon-insights/amazon-review-insights:latest
